main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name="logout"),
    path('login/', views.login_request, name="login"),
    path("<single_slug>", views.single_slug, name="single_slug"),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('',include('main.urls')),
	path('tinymce/',include('tinymce.urls')),
        path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class TutorialCategory(models.Model):
	category 	= models.CharField(max_length=200)
	summery 	= models.CharField(max_length=200)
	slug 		= models.CharField(max_length=200)
	
	class Meta:
		verbose_name_plural = "categories"

	def __str__(self):
		return self.category


class TutorialSeries(models.Model):
	tutorial_series  	= models.CharField(max_length=200)
	tutorial_category	= models.ForeignKey(TutorialCategory, default=1, verbose_name="category", on_delete=models.SET_DEFAULT)
	series_summery  	= models.CharField(max_length=200)
	
	class Meta:
		verbose_name_plural = "series"

	def __str__(self):
		return self.tutorial_series



class Tutorial(models.Model):
	tutorial_title 		= models.CharField(max_length=200)
	tutorial_content 	= models.TextField()
	tutorial_published 	= models.DateTimeField("date puplished:")
	tutorial_series		= models.ForeignKey(TutorialSeries, default=1, verbose_name="series", on_delete=models.SET_DEFAULT)
	tutorial_slug 		= models.CharField(max_length=200, unique=True)



	def __str__(self):
		return self.tutorial_title

	# def save(self, **kwargs):
	# 	tutorial_slug = '%s' % (self.tutorial_title)
	# 	unique_slugify(self, tutorial_slug)
	# 	super(Tutorial, self).save()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)


	class meta:
		model  = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user= super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data["email"]
		if commit:
			user.save()
		return user

main/views.py
from django.shortcuts import render, redirect
from .models import Tutorial, TutorialCategory, TutorialSeries
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from .forms import NewUserForm
from django.http import HttpResponse
from django.contrib.auth.models import User

def single_slug(request, single_slug):
    # first check to see if the url is in categories.

    categories = [c.slug for c in TutorialCategory.objects.all()]
    if single_slug in categories:
        matching_series = TutorialSeries.objects.filter(tutorial_category__slug=single_slug)
        series_urls = {}

        for m in matching_series.all():
            part_one = Tutorial.objects.filter(tutorial_series__tutorial_series=m.tutorial_series).earliest("tutorial_published")
            series_urls[m] = part_one.tutorial_slug

        return render(request=request,
                      template_name='main/category.html',
                      context={"tutorial_series": matching_series, "part_ones": series_urls})
    tutorials = [t.tutorial_slug for t in Tutorial.objects.all()]
    if single_slug in tutorials:
        this_tutorial = Tutorial.objects.get(tutorial_slug=single_slug)
        tutorials_from_series = Tutorial.objects.filter(tutorial_series__tutorial_series=this_tutorial.tutorial_series).order_by('tutorial_published')
        this_tutorial_idx = list(tutorials_from_series).index(this_tutorial)

        return render(request=request,
        	template_name='main/tutorial.html',
                      context={"tutorial": this_tutorial,
                      "sidebar": tutorials_from_series,
                      "this_tut_idx": this_tutorial_idx})
    return render(request=request,
        	template_name='main/tutorial.html',
                      context={'categories':categories})
# def single_slug(request, single_slug):
# 	categories = [c.slug for c in TutorialCategory.objects.all()]
	
# 	if single_slug in categories:
# 		matching_series =TutorialSeries.objects.filter(tutorial_category__slug= single_slug)
# 		series_urls = { }
# 		for m in matching_series.all():
# 			part_one = Tutorial.objects.filter(tutorial_series__tutorial_series= m.tutorial_series).earliest("tutorial_published")
# 			series_urls[m] = part_one.tutorial_slug
# 		return render(request, "main/category.html", {"tutorial_series":matching_series, "part_ones": series_urls})
	
# 	tutorials = [t.tutorial_slug for t in Tutorial.objects.all()]
# 	if single_slug in tutorials:
# 		this_tutorial=Tutorial.objects.get(tutorial_slug= single_slug)
# 		tutorials_from_series= Tutorial.objects.filter(tutorial_series__tutorial_series=this_tutorial.tutorial_series).order_by("tutorial_published")
# 		this_tutorial_idx= list(tutorials_from_series).index(this_tutorial)

		
	# return render(request,
	# 				  "main/tutorial.html",
	# 				  {"tutorial": this_tutorial,
	# 				   "sidebar": tutorials_from_series,
	# 				    "this_tutorial_idx": this_tutorial_idx })
	


def homepage(request):
	return render(request=request, template_name="main/categories.html",
					context={"categories":TutorialCategory.objects.all})



def register(request):
	if request.method == 'POST':
		form = NewUserForm(request.POST or None)
		if form.is_valid():
				print(form.cleaned_data)
				username = form.cleaned_data.get("username")
				email 	 = form.cleaned_data.get("email")
				password = form.cleaned_data.get("password")
				
				new_user = User.objects.create_user(username, email, password)
				print(new_user)
		#User.objects.create_user(username, email, password)
	form = NewUserForm()
	return render(request = request,
                  template_name = "main/register.html",
                  context={"form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "logged out succesfully!")
	return redirect("main:homepage")

def login_request(request):
	if request.method == 'POST':
		form = AuthenticationForm(request=request, data=request.POST)
		if form.is_valid():
			username= form.cleaned_data.get("username")
			password= form.cleaned_data.get("password")
			user =authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.success(request, f"You have logged in as {username}")
				return redirect("main:homepage")
			else:
				messages.error(request, "Invalid username or password.")
		else:
			messages.error(request, "Invalid username or password.")


	form = AuthenticationForm()
	
	return render(request, "main/login.html", {"form":form})

main/templates/includes/messages.html
 {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
            {% elif message.tags == 'info'%}
                <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
            {% elif message.tags == 'warning'%}
                <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
            {% endif %}
        {% endfor %}
{% endif %}

main/templates/includes/navbar.html
 <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Tutorials!</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'main:logout'%}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'main:register'%}">Register</a></li>
          <li><a href="{% url 'main:login' %}">Login</a></li>
         {% endif %}
      </ul>
    </div>
  </nav>

main/templates/main/categories.html
{% extends 'main/header.html' %}

{% block content%}   
        <div class="row">
       {% for cat in categories %}
            <div class="col s12 m6 l4">
                <a href="{{cat.slug}}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{cat.category}}</div>
                            <!--<p style="font-size:70%">Published {{tut.tutorial_published}}</p>-->
                            <p>{{cat.summery}}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/category.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="row">
        {% for tut, partone in part_ones.items %}

            <div class="col s12 m6 l4">
                <a href="{{partone}}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{tut.tutorial_series}}</div>
                            <!--<p style="font-size:70%">Published {{tut.tutorial_published}}</p>-->
                            <p>{{tut.series_summary}}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/header.html
<head>
    {% load static %}
    <!-- Prism CSS -->
    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'main/css/materialize.css' %}">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
</head>
<body>
  {% include "includes/navbar.html" %}
  
   
  <div class="container">
      {% block content %}
      {% endblock %}
  </div>
</body>
{% include "includes/messages.html" %}
<script src="{% static 'tinymce/js/prism.js' %}"></script>
   
<script>M.AutoInit();</script> 

main/templates/main/home.html
{% extends 'main/header.html' %}

{% block content%}

	
		
     
  <div class="row">
  	{% for tut in tutorials %}
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{ tut.tutorial_title}}</span>
          <p style="font-size:70%">{{ tut.tutorial_published}}</p>
          <p>{{ tut.tutorial_content|safe}}</p>
        </div>
        <div class="card-action">
          <a href="#">Visit</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>



    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{ tut.tutorial_title}}</span>
          <p style="font-size:70%">{{ tut.tutorial_published}}</p>
          <p>{{ tut.tutorial_content|safe}}</p>
        </div>
        <div class="card-action">
          <a href="#">Visit</a>
        </div>
      </div>
    </div>


  </div>
  {% endblock %}

main/templates/main/login.html
{% extends 'main/header.html' %}

{% block content%}

<br>
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn" type="submit">Login</button>
  </form>
  Don't have account?<a href="/register"><b> Register </b></a> 
</div>
  {% endblock %}

main/templates/main/register.html
{% extends 'main/header.html' %}

{% block content%}
<br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn" type="submit">Register</button>
  </form>
  If You already have an account,<a href="/login"><b> Login</b></a> instead.
  {% endblock %}

main/templates/main/tutorial.html
 {% extends 'main/header.html' %}

  {% block content %}

    <div class="row">

        <div class="col s12, m8, l8">
            <h3>{{tutorial.tutorial_title}}</h3>
            <p style="font-size:70%">Published {{tutorial.tutorial_published}}</p>
            {{tutorial.tutorial_content|safe}}
        </div>

        <div class="col s12 m4 l4">
            <ul class="collapsible popout">
                {% for tutorial in sidebar %}
                    {% if forloop.counter == this_tutorial_idx %}
                        <li class="active">
                            <div class="collapsible-header">{{tutorial.tutorial_title}}<br>(currently viewing)</div>
                        </li>
                    {% else %}
                        <li>
                            <div class="collapsible-header">{{tutorial.tutorial_title}}</div>
                            <div class="collapsible-body">
                                <p><a href="/{{tutorial.tutorial_slug}}"><button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Go</button></a></p>

                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>

    </div>

{% endblock %}